### PR TITLE
icinga2: Common Muted Event for Acknowledgements w/o Comments during Catch-Up

### LINKED ISSUE #245: Icinga 2 source does not work if any acknowledged checkable misses the corresponding comment
When any Icinga 2 host or service is acknowledged, but the corresponding comment went missing, the following happens and the Icinga 2 Event Stream Source fails to properly start working:

```
2024-07-19T11:28:27.409Z	INFO	icinga2	Start listening on Icinga 2 Event Stream	{"source_id": 1}
2024-07-19T11:28:27.409Z	INFO	icinga2	Worker enters catch-up-phase, start caching up on Event Stream events	{"source_id": 1}
2024-07-19T11:28:32.550Z	WARN	icinga2	Catch-up-phase was interrupted by an error, another attempt will be made	{"source_id": 1, "error": "fetching acknowledgement comment for \"master-1!icinga-cluster\" failed, found no ACK Comments for \"comment.entry_type == 4 && comment.host_name == comment_host_name && comment.service_name == comment_service_name\" with map[comment_host_name:master-1 comment_service_name:icinga-cluster]", "delay": "1s"}
2024-07-19T11:28:32.550Z	INFO	icinga2	Worker enters catch-up-phase, start caching up on Event Stream events	{"source_id": 1}
2024-07-19T11:28:35.921Z	WARN	icinga2	Catch-up-phase was interrupted by an error, another attempt will be made	{"source_id": 1, "error": "fetching acknowledgement comment for \"master-1!icinga-cluster\" failed, found no ACK Comments for \"comment.entry_type == 4 && comment.host_name == comment_host_name && comment.service_name == comment_service_name\" with map[comment_host_name:master-1 comment_service_name:icinga-cluster]", "delay": "2s"}
2024-07-19T11:28:35.921Z	INFO	icinga2	Worker enters catch-up-phase, start caching up on Event Stream events	{"source_id": 1}
2024-07-19T11:28:40.419Z	WARN	icinga2	Catch-up-phase was interrupted by an error, another attempt will be made	{"source_id": 1, "error": "fetching acknowledgement comment for \"master-1!icinga-cluster\" failed, found no ACK Comments for \"comment.entry_type == 4 && comment.host_name == comment_host_name && comment.service_name == comment_service_name\" with map[comment_host_name:master-1 comment_service_name:icinga-cluster]", "delay": "4s"}
2024-07-19T11:28:40.419Z	INFO	icinga2	Worker enters catch-up-phase, start caching up on Event Stream events	{"source_id": 1}
2024-07-19T11:28:46.673Z	WARN	icinga2	Catch-up-phase was interrupted by an error, another attempt will be made	{"source_id": 1, "error": "fetching acknowledgement comment for \"master-1!icinga-cluster\" failed, found no ACK Comments for \"comment.entry_type == 4 && comment.host_name == comment_host_name && comment.service_name == comment_service_name\" with map[comment_host_name:master-1 comment_service_name:icinga-cluster]", "delay": "8s"}
2024-07-19T11:28:46.673Z	INFO	icinga2	Worker enters catch-up-phase, start caching up on Event Stream events	{"source_id": 1}
2024-07-19T11:28:57.109Z	WARN	icinga2	Catch-up-phase was interrupted by an error, another attempt will be made	{"source_id": 1, "error": "fetching acknowledgement comment for \"master-1!icinga-cluster\" failed, found no ACK Comments for \"comment.entry_type == 4 && comment.host_name == comment_host_name && comment.service_name == comment_service_name\" with map[comment_host_name:master-1 comment_service_name:icinga-cluster]", "delay": "16s"}
2024-07-19T11:28:57.109Z	INFO	icinga2	Worker enters catch-up-phase, start caching up on Event Stream events	{"source_id": 1}
2024-07-19T11:29:15.270Z	WARN	icinga2	Catch-up-phase was interrupted by an error, another attempt will be made	{"source_id": 1, "error": "fetching acknowledgement comment for \"master-1!icinga-cluster\" failed, found no ACK Comments for \"comment.entry_type == 4 && comment.host_name == comment_host_name && comment.service_name == comment_service_name\" with map[comment_host_name:master-1 comment_service_name:icinga-cluster]", "delay": "32s"}
2024-07-19T11:29:15.270Z	INFO	icinga2	Worker enters catch-up-phase, start caching up on Event Stream events	{"source_id": 1}
2024-07-19T11:29:49.188Z	WARN	icinga2	Catch-up-phase was interrupted by an error, another attempt will be made	{"source_id": 1, "error": "fetching acknowledgement comment for \"master-1!icinga-cluster\" failed, found no ACK Comments for \"comment.entry_type == 4 && comment.host_name == comment_host_name && comment.service_name == comment_service_name\" with map[comment_host_name:master-1 comment_service_name:icinga-cluster]", "delay": "1m4s"}
2024-07-19T11:29:49.188Z	INFO	icinga2	Worker enters catch-up-phase, start caching up on Event Stream events	{"source_id": 1}
2024-07-19T11:30:56.037Z	WARN	icinga2	Catch-up-phase was interrupted by an error, another attempt will be made	{"source_id": 1, "error": "fetching acknowledgement comment for \"master-1!icinga-cluster\" failed, found no ACK Comments for \"comment.entry_type == 4 && comment.host_name == comment_host_name && comment.service_name == comment_service_name\" with map[comment_host_name:master-1 comment_service_name:icinga-cluster]", "delay": "2m8s"}
2024-07-19T11:30:56.037Z	INFO	icinga2	Worker enters catch-up-phase, start caching up on Event Stream events	{"source_id": 1}
2024-07-19T11:33:06.841Z	WARN	icinga2	Catch-up-phase was interrupted by an error, another attempt will be made	{"source_id": 1, "error": "fetching acknowledgement comment for \"master-1!icinga-cluster\" failed, found no ACK Comments for \"comment.entry_type == 4 && comment.host_name == comment_host_name && comment.service_name == comment_service_name\" with map[comment_host_name:master-1 comment_service_name:icinga-cluster]", "delay": "3m0s"}
2024-07-19T11:33:06.841Z	INFO	icinga2	Worker enters catch-up-phase, start caching up on Event Stream events	{"source_id": 1}
```

This Situation can easily be created manually by acknowledging something and then deleting the corresponding comment from Icinga Web (this currently does not clear the acknowledgment, see also https://github.com/Icinga/icinga2/issues/8896), however, I'm quite certain that I didn't do this, so maybe there's even an "Icinga 2 forgets ack comments" bug here as well.

Anyways, the current error handling for this situation is too aggressive, this should not make the whole catch-up phase fail.

### PR DESCRIPTION
**Pull request by oxzi**
When creating an acknowledgement in Icinga Web, a comment is also added. It is possible, however, to later delete the comment while keeping the object acknowledged.

Deleting acknowledgement comments was not an expected behavior, requiring the presence of an associated comment for each acknowledgement. Otherwise, the catch-up-phase would not succeed.

Unfortunately, there is no way to later add an author to an acknowledgement unless a matching comment exists. Thus, the catch-up-phase will now generalize this acknowledgement into a common muted event, missing the details available in the comment.

Closes #245.

### CODE REVIEW

File: internal/icinga2/client_api.go [hunk 1]
```diff
@@ -306,7 +318,26 @@ func (client *Client) checkMissedChanges(ctx context.Context, objType string, ca
...
+				// Incident.processAcknowledgementEvent method will fail hard.
+				//
+				// As this very case only happens for catch-ups, one can at least hope that Icinga Notifications was
+				// notified about the AcknowledgementSet event through the Event Stream API when it happened. There
+				// might be a good chance that some manager was already assigned.
+
+				client.Logger.Warnw(
+					"Cannot find the comment for an acknowledgement, skipping this acknowledgement as the authorship is missing",
+					zap.String("object", objectName), zap.Error(err))
+				continue
```
Comment (julianbrost) [inline internal/icinga2/client_api.go:339]: Instead of just skipping the object, please consider submitting a "basic" mute event like done there, that would at least get the mute state correct:

https://github.com/Icinga/icinga-notifications/blob/388732218bcaf20b07876c5d2fc2fe865f3857b0/internal/icinga2/client_api.go#L327-L332

File: internal/icinga2/client_api.go [hunk 2]
```diff
@@ -212,17 +213,28 @@ func (client *Client) fetchCheckable(ctx context.Context, host, service string)
 	return &objQueriesResults[0], nil
 }
 
+// fetchAcknowledgementCommentNoComment is an error indicating that no Comment for an Acknowledgement exists.
+//
+// This error should only be wrapped and returned from the fetchAcknowledgementComment method and only if no Comment was
+// found. For other errors, like network errors, this error must not be used.
+var fetchAcknowledgementCommentNoComment = errors.New("found no Acknowledgement Comment")
```
Comment (julianbrost) [inline internal/icinga2/client_api.go:220]: Something less convoluted should do as variable name as well, something like `missingAcknowledgeComment`.

File: internal/icinga2/client_api.go (hunk 1 above)
Comment (yhabteab) [reply internal/icinga2/client_api.go:339]: This will also allow you to keep the existing event processing flow and not skip the state change event below just because you could not find an ack comment.

File: internal/icinga2/client_api.go (hunk 2 above)
Comment (yhabteab) [reply internal/icinga2/client_api.go:220]: Please also prefix it with an `err`.

File: internal/icinga2/client_api.go [hunk 3]
```diff
@@ -306,17 +318,38 @@ func (client *Client) checkMissedChanges(ctx context.Context, objType string, ca
...
+				// acknowledgement to a contact, when being fetched through the Config Objects API, is to find a
+				// matching Comment object, which contains an author field.
+				//
+				// This is not the case for the Event Stream API, where AcknowledgementSet has an author field.
+				//
+				// However, when no author is present, the Acknowledgement Event cannot be processed. Eventually, the
+				// Incident.processAcknowledgementEvent method will fail hard.
+
+				client.Logger.Infow("Cannot find the comment for an acknowledgement, creating a generic muted event",
+					zap.String("object", objectName), zap.Error(err))
```
Comment (yhabteab) [inline internal/icinga2/client_api.go:333]: It doesn't make sense to include the `zap.Error()` field in an info level, and since it doesn't contain any special information other than the same set of info being logged there, I would just drop it.

File: internal/icinga2/client_api.go [hunk 4]
```diff
@@ -306,17 +318,38 @@ func (client *Client) checkMissedChanges(ctx context.Context, objType string, ca
...
 
-			ack := &Acknowledgement{Host: hostName, Service: serviceName, Author: ackComment.Author, Comment: ackComment.Text}
-			// We do not need to fake ACK set events as they are handled correctly by an incident and any
-			// redundant/successive ACK set events are discarded accordingly.
-			ack.EventType = typeAcknowledgementSet
-			fakeEv, err = client.buildAcknowledgementEvent(ctx, ack)
-			if err != nil {
-				return fmt.Errorf("failed to construct Event from Acknowledgement response, %w", err)
+				fakeEv.Type = event.TypeMute
+				fakeEv.SetMute(false, "Acknowledgement event without corresponding comment")
```
Comment (yhabteab) [inline internal/icinga2/client_api.go:341]: Why are you generating a fake `mute` event without setting its `mute` flag to true? This event type combination is considered to be invalid by the way, but since we do not validate all the events from the Icinga 2 package, you got passed through without an error, otherwise you would have run into this problem.
https://github.com/Icinga/icinga-notifications/blob/388732218bcaf20b07876c5d2fc2fe865f3857b0/internal/event/event.go#L92-L94

I would also use something like this as a mute reason: `Checkable is acknowledged, but we could not find its corresponding comment`

File: internal/icinga2/client_api.go (hunk 3 above)
Comment (oxzi) [reply internal/icinga2/client_api.go:333]: It actually contains a bit more information, indicating if there is no acknowledgment comment at all or none in the arbitrary chosen time frame of a second. As the latter feels like something were some day a bug might lurk, I would like to keep this information included.

I have changed the field type from an `Error` to a `NamedError`, naming it "reason" so no error appears on info level.

Comment (julianbrost) [reply internal/icinga2/client_api.go]: > It actually contains a bit more information, indicating if there is no acknowledgment comment at all or none in the arbitrary chosen time frame of a second. As the latter feels like something were some day a bug might lurk, I would like to keep this information included.

The now updated log messages look fine to me, just FYI: that might just tell you if an acknowledgement with a persistent comment was created some time in the past (at least, that's how you can easily make it log the other message)

**Review by julianbrost — APPROVED** [review]

**Review by yhabteab — APPROVED** [review]
